### ISSUE TITLE
CharLengthAttribute没有包含在项目中

### ISSUE THREAD

**Issue by taohonggou** [SkyChenSky/Sikiro.Tookits#1]
我刚下载下项目来，发现Attribute文件夹中没有CharLengthAttribute，是故意这样的吗？

**Comment by SkyChenSky** [comment]
CharLengthAttribute是在另外一个项目，如果你需要我可以打包给你。我这次没打算开放Mvc的封装，不知道你是在哪见到CharLengthAttribute的？

**Comment by taohonggou** [comment]
我刚又看项目中没有了，看你在刚才的提交中见他删除了，这个不是问题，就是偶尔看到了。谢谢分享奥，赞一个
![image](https://user-images.githubusercontent.com/13165397/29058321-553e8bc0-7c42-11e7-8ab0-99968eb05b37.png)

**Comment by SkyChenSky** [comment]
噢。。这个是我之前遗留的，迁到另外一个项目去了，不好意思，欢迎随时提意见
